[versions]

kotlin = "2.0.21"

javafx = "22.0.1"

javafx-plugin = "0.1.0"

kotlinx-coroutines = "1.9.0"


[libraries]

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

kotlinx-coroutines-javafx = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-javafx", version.ref = "kotlinx-coroutines" }


[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafx-plugin" }
