name: Build and test application

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.10", "3.11" ]
    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Build backend"
        run: make build-backend
      - name: "Install app dependencies"
        run: make install-deps
      - name: "Test backend"
        run: make test-backend
      - name: "Check frontend formating with black"
        run: make check-frontend-formatting
      - name: "Check frontend with mypy"
        run: make check-frontend-linting
