name: Build and test application

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.10", "3.11" ]
    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Build backend"
        run: make build-backend
      - name: "Install app dependencies"
        run: make install-deps
      - name: "Install Qt Dependencies (Ubuntu)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libegl1-mesa \
            libegl1 \
            libxkbcommon-x11-0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render-util0 \
            libxcb-shape0 \
            libxcb-xinerama0 \
            libxcb-xfixes0 \
            x11-utils \
            libdbus-1-3
      - name: "Check frontend formating with black"
        run: make check-frontend-formatting
      - name: "Check frontend with mypy"
        run: make check-frontend-linting
      - name: "Test app"
        run: make test
