name: Release

on:
  push:
# TODO : Uncomment after tests
#    tags:
#      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Python 3.11"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: "Install libs for Qt on Ubuntu"
        if: matrix.os == 'ubuntu-latest'
        run: >
          sudo apt install -y
          build-essential
          libgl1-mesa-dev
          libgstreamer-gl1.0-0
          libpulse-dev
          libxcb-glx0
          libxcb-icccm4
          libxcb-image0
          libxcb-keysyms1
          libxcb-randr0
          libxcb-render-util0
          libxcb-render0
          libxcb-shape0
          libxcb-shm0
          libxcb-sync1
          libxcb-util1
          libxcb-xfixes0
          libxcb-xinerama0
          libxcb1
          libxkbcommon-dev
          libxkbcommon-x11-0
          libxcb-xkb-dev
          libxcb-cursor0
      - name: "Build and check app"
        run: make build check
      - name: "Upload artifact"
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: "drunk-cats-${{ matrix.os }}"
          path: "./drunk-cats"
      - name: "Upload artifact"
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: "drunk-cats-${{ matrix.os }}"
          path: "./drunk-cats.exe"
